#!/usr/bin/env python3
"""Render + verify the machine-readable system dependency graph.

The graph lives in `system-graph.yml` (repo root, next to `repos.yml`):
`repos.yml` is the INVENTORY (nodes only — which repos exist, where);
`system-graph.yml` is the MODEL (nodes AND edges — what depends on, reads,
writes, invokes, gates what). This script is the only writer of the rendered
mermaid block in `000-docs/020-AT-SMAP-system-dependency-graph.md`, between
AUTOGEN markers — the same discipline as `bin/teamkb-systemmap.sh` and the
live-stats block in `005-AT-ARCH`.

Why a generator + sync check instead of a hand-drawn diagram: this estate has
been bitten repeatedly by maps that silently diverged from reality (the
six-day eval quiet-skip, the gitignored dense floor). A diagram nobody can
diff rots invisibly; a YAML model with a CI job that fails when the rendered
doc drifts from the model cannot rot invisibly. The practice is
architecture-as-code; the CI sync job is an architectural fitness function.

Modes:
  --write        render mermaid from the YAML into the doc (between markers)
  --check        exit 1 if the doc's rendered block differs from the YAML
                 (CI mode — also runs all structural validation)
  --check-local  additionally verify `local` assertions (systemd units, cron
                 lines, paths) against THIS box. Meaningful only on the dev
                 box; CI must not run it (GitHub runners have none of these).

Edge tiers:
  derived   — mechanically checkable facts (a package.json dep, a systemd
              unit, a crontab line). --check-local re-verifies these.
  semantic  — hand-curated invariants no tool can derive (e.g. "the eval
              must never consume the serving policy"). These carry the
              guard that enforces them in `evidence` so a reader can find
              the test/lint that keeps them true.

Exit codes: 0 ok · 1 validation/sync failure · 2 usage/environment error.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("FATAL: PyYAML required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

ROOT = Path(__file__).resolve().parent.parent
GRAPH = ROOT / "system-graph.yml"
DOC = ROOT / "000-docs" / "020-AT-SMAP-system-dependency-graph.md"

BEGIN = "<!-- AUTOGEN:system-graph — regenerated by scripts/render-system-graph.py; DO NOT hand-edit between the markers -->"
END = "<!-- /AUTOGEN:system-graph -->"

NODE_KINDS = {
    "repo", "package", "app", "service", "timer", "cron",
    "script", "datastore", "artifact", "gate", "external",
}
EDGE_KINDS = {"depends-on", "reads", "writes", "invokes", "gates", "mirrors", "backs-up"}
EDGE_TIERS = {"derived", "semantic"}

# Mermaid ids must be alphanumeric/underscore; our node ids are kebab-case.
def mid(node_id: str) -> str:
    return node_id.replace("-", "_").replace(".", "_")


def fail(errors: list[str]) -> None:
    for e in errors:
        print(f"ERROR: {e}", file=sys.stderr)
    sys.exit(1)


def load() -> dict:
    if not GRAPH.exists():
        fail([f"{GRAPH} not found"])
    data = yaml.safe_load(GRAPH.read_text())
    errors: list[str] = []

    layers = data.get("layers") or []
    nodes = data.get("nodes") or []
    edges = data.get("edges") or []

    ids: set[str] = set()
    # Mermaid ids are the NORMALIZED form (mid() maps '-' and '.' to '_'), so
    # `foo-bar`, `foo.bar`, and `foo_bar` would silently render as ONE node —
    # distinct model nodes merging in the diagram with CI still green. Reject
    # the collision at validation instead (CodeRabbit finding, PR #78).
    normalized: dict[str, str] = {}
    for n in nodes:
        nid = n.get("id", "")
        if not nid:
            errors.append(f"node without id: {n}")
            continue
        if nid in ids:
            errors.append(f"duplicate node id: {nid}")
        ids.add(nid)
        m = mid(nid)
        if m in normalized and normalized[m] != nid:
            errors.append(
                f"node ids {normalized[m]!r} and {nid!r} collide after mermaid "
                f"normalization ({m!r}) — rename one"
            )
        normalized[m] = nid
        if n.get("kind") not in NODE_KINDS:
            errors.append(f"node {nid}: bad kind {n.get('kind')!r}")
        if n.get("layer") not in layers:
            errors.append(f"node {nid}: layer {n.get('layer')!r} not in layers list")
        if not n.get("locus"):
            errors.append(f"node {nid}: missing locus")

    for e in edges:
        frm, to = e.get("from"), e.get("to")
        if frm not in ids:
            errors.append(f"edge {frm}->{to}: unknown 'from' node")
        if to not in ids:
            errors.append(f"edge {frm}->{to}: unknown 'to' node")
        if e.get("kind") not in EDGE_KINDS:
            errors.append(f"edge {frm}->{to}: bad kind {e.get('kind')!r}")
        if e.get("tier") not in EDGE_TIERS:
            errors.append(f"edge {frm}->{to}: bad tier {e.get('tier')!r}")
        # An edge nobody can verify is an opinion, not a model. Derived edges
        # cite the mechanical fact; semantic edges cite the guard that
        # enforces the invariant.
        if not e.get("evidence"):
            errors.append(f"edge {frm}->{to}: missing evidence")

    if errors:
        fail(errors)
    return data


def render(data: dict) -> str:
    lines = ["```mermaid", "graph LR"]
    by_layer: dict[str, list[dict]] = {}
    for n in data["nodes"]:
        by_layer.setdefault(n["layer"], []).append(n)

    for layer in data["layers"]:
        members = by_layer.get(layer, [])
        if not members:
            continue
        lines.append(f"  subgraph {mid(layer)}[{layer}]")
        for n in members:
            label = n["id"] if len(n["id"]) <= 24 else n["id"][:22] + "…"
            lines.append(f'    {mid(n["id"])}["{label}"]')
        lines.append("  end")

    for e in data["edges"]:
        arrow = "-.->" if e["tier"] == "semantic" else "-->"
        # Label non-dependency kinds; plain depends-on stays unlabeled to keep
        # the diagram readable.
        if e["kind"] == "depends-on":
            lines.append(f'  {mid(e["from"])} {arrow} {mid(e["to"])}')
        else:
            lines.append(f'  {mid(e["from"])} {arrow}|{e["kind"]}| {mid(e["to"])}')

    lines.append("```")
    stats = (
        f"\n_{len(data['nodes'])} nodes · {len(data['edges'])} edges "
        f"({sum(1 for e in data['edges'] if e['tier'] == 'derived')} derived / "
        f"{sum(1 for e in data['edges'] if e['tier'] == 'semantic')} semantic) · "
        "solid = mechanically derived · dotted = hand-curated invariant_\n"
    )
    return "\n".join(lines) + "\n" + stats


def splice(doc_text: str, block: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(doc_text):
        fail([f"AUTOGEN markers not found in {DOC}"])
    return pattern.sub(BEGIN + "\n\n" + block + "\n" + END, doc_text)


def check_local(data: dict) -> list[str]:
    """Verify box-tier assertions. Only meaningful on the dev box."""
    problems: list[str] = []
    crontab = subprocess.run(
        ["crontab", "-l"], capture_output=True, text=True
    ).stdout
    for n in data["nodes"]:
        local = n.get("local") or {}
        unit = local.get("unit")
        if unit:
            r = subprocess.run(
                ["systemctl", "--user", "cat", unit],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                problems.append(f"{n['id']}: systemd unit {unit} not found on this box")
        cron = local.get("cron")
        if cron and cron not in crontab:
            problems.append(f"{n['id']}: crontab does not contain {cron!r}")
        path = local.get("path")
        if path and not Path(path).expanduser().exists():
            problems.append(f"{n['id']}: path {path} does not exist on this box")
    return problems


def main() -> None:
    args = set(sys.argv[1:])
    if not args or not args <= {"--write", "--check", "--check-local"}:
        print(__doc__, file=sys.stderr)
        sys.exit(2)

    data = load()
    block = render(data)
    doc_text = DOC.read_text() if DOC.exists() else fail([f"{DOC} not found"])

    if "--write" in args:
        DOC.write_text(splice(doc_text, block))
        print(f"wrote {DOC.relative_to(ROOT)}")

    if "--check" in args:
        if splice(doc_text, block) != doc_text:
            fail([
                f"{DOC.name} is out of sync with system-graph.yml — "
                "run: python3 scripts/render-system-graph.py --write",
            ])
        print("check OK: doc matches model")

    if "--check-local" in args:
        problems = check_local(data)
        if problems:
            fail(problems)
        print("check-local OK: box reality matches derived assertions")


if __name__ == "__main__":
    main()
